version: '3.1'

services:
  # db:
  #   image: mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 123456
  #     MYSQL_DATABASE: markettermdb
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password123
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./volumes/mysql:/var/lib/mysql

  ## MongoDB
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  
  ## Mongo Express
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017

  ## Solution: Marketterm
  marketterm:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    depends_on:
      - mongo