version: '3'

services:
  ## MongoDB
  mongo:
    image: mongo
    restart: always
    environment:
       - MONGO_INITDB_ROOT_USERNAME=admin
       - MONGO_INITDB_ROOT_PASSWORD=password
       - MONGO_INITDB_DATABASE=markettermdb
    volumes:
      - ./mongodb_data:/data/db
  
## Mongo Express
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password@mongo:27017/?authSource=admin
    depends_on:
      - mongo

## Solution: Marketterm
  marketterm:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    depends_on:
      - mongo

## Volumes
  
volumes:
  mongodb_data:
    driver: local